services:
  postgres_cadastro:
    container_name: postgres_cadastro_fiqfit_Workout
    image: postgres:12.2
    environment:
      POSTGRES_USER: cadastro
      POSTGRES_PASSWORD: cadastro
    ports:
      - 5432:5432